version: '3'

services:

  flask:
    container_name: flask
    build: ./flask
    ports:
     - "8000:5000"
    volumes:
     - ./flask/:/code
    depends_on:
     - redis
     - mongodb
    environment:
     - DB=mongodb://mongodb:27017

  redis:
    container_name: redis
    image: redis

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx/overwrite.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
     - flask

  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - ./mongo/db:/data/db
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: password
    ports:
    - 27017:27017